mcc: '001'
mnc: '01'

nci: '0x000000010'
idLength: 32
tac: 1

linkIp: 10.3.0.10
ngapIp: 10.3.0.10
gtpIp: 10.3.0.10

amfConfigs:
  - address: 10.3.0.2
    port: 38412

slices:
  - sst: 1
    sd: 0x102030

ignoreStreamIds: true