supi: 'imsi-001013657756211'

mcc: '001'
mnc: '01'

protectionScheme: 0

routingIndicator: '0000'

key: 'b88f01088ca45c301921f771a93f8688'

op: 'a131974988e18bce1568853e84d99e3d'
opType: 'OPC'

amf: '8000'

imei: '001017994095263'

tunNetmask: '255.255.255.0'

gnbSearchList:
  - 10.3.0.10   

sessions:
  - type: 'IPv4'
    apn: 'internet'
    slice:
      sst: 1
      sd: 0x102030

configured-nssai:
  - sst: 1
    sd: 0x102030

default-nssai:
  - sst: 1
    sd: 0x102030

integrity:
  IA1: true
  IA2: true
  IA3: true

ciphering:
  EA1: true
  EA2: true
  EA3: true

integrityMaxRate:
  uplink: 'full'
  downlink: 'full'

uacAic:
  mps: false
  mcs: false

uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false
